SELECT  Count(kategoria)  
FROM dziekanat.wojsko 
WHERE wojsko.kategoria='A'
UNION ALL
SELECT  Count(kategoria)  
FROM dziekanat.wojsko 
WHERE wojsko.kategoria='B'
UNION ALL
SELECT Count(kategoria)
FROM dziekanat.wojsko
WHERE wojsko.kategoria='C'
UNION ALL
SELECT Count(kategoria)
FROM dziekanat.wojsko
WHERE wojsko.kategoria='D'
UNION ALL
SELECT Count(kategoria)
FROM dziekanat.wojsko
WHERE wojsko.kategoria='E'
